name: 'PAYAM AIR '
favicon: null
layout_spectrum: 0.75529
typography_spectrum: 0.639801234472543
title: Payam Air Space Agency
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#2c6ab5'
    - '#88abd5'
    - '#f1f5fa'
    - '#dde7f3'
  brandStrength: 0.2864492617081851
  lightness: 0.2597544987220317
  saturation: 0.4983164402656257
  rhythmicContrast: 0.622985562775284
purpose: []
