name: 'PAYAM AIR '
favicon: null
layout_spectrum: 0.50034
typography_spectrum: 0.639801234472543
title: Payam Air Space Agency
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#2c6ab5'
    - '#88abd5'
    - '#f1f5fa'
    - '#dde7f3'
  brandStrength: 1
  lightness: 0.875
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
